---
# tasks for hoko
- user: name=hoko

- group: name=hoko

- get_url: url=https://github.com/tmtk75/hoko/releases/download/v{{ hoko_version }}/hoko-{{ hoko_version }}_linux_amd64.zip
  args:
    dest: /tmp/hoko-{{ hoko_version }}_linux_amd64.zip
    mode: 0644
    sha256sum: "{{ sha256sum }}"

- command: unzip -o /tmp/hoko-{{ hoko_version }}_linux_amd64.zip chdir=/usr/local/bin

- file: path=/usr/local/bin/hoko owner=hoko group=hoko mode=0755 state=file

- file: path={{ item }} owner=hoko group=hoko mode=0755 state=directory
  with_items:
    - /etc/hoko.d

- copy: src=./etc/init.d/hoko dest=/etc/init.d/hoko owner=hoko group=hoko mode=0755

- template: src={{ hoko_conf }} dest=/etc/hoko.conf owner=hoko group=hoko mode=0644
- template: src={{ serf_conf }} dest=/etc/hoko.d/serf.conf owner=hoko group=hoko mode=0644
- template: src={{ sysconfig }} dest=/etc/sysconfig/hoko owner=hoko group=hoko mode=0644

- template: src=.{{ item }} dest={{ item }} owner=hoko group=hoko mode=0755
  with_items:
    - /etc/hoko.d/echo.sh

- service: name=hoko state=started enabled=yes

